"""add is_removed to transactions

Revision ID: 145da5c15d76
Revises: 5a26caa258aa
Create Date: 2026-02-05 13:50:24.719273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145da5c15d76'
down_revision: Union[str, Sequence[str], None] = '5a26caa258aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with server_default so existing rows get False (no NOT NULL violation)
    op.add_column(
        'transactions',
        sa.Column('is_removed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_removed')
    # ### end Alembic commands ###
