"""updated plaid items

Revision ID: 5a26caa258aa
Revises: 3a635863128f
Create Date: 2026-01-30 17:23:17.432015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a26caa258aa'
down_revision: Union[str, Sequence[str], None] = '3a635863128f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_items', sa.Column('cursor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_items', 'cursor')
    # ### end Alembic commands ###
