"""add provider transaction identifiers

Revision ID: b219dbac2f23
Revises: f606535d5796
Create Date: 2026-01-29 16:52:09.113771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b219dbac2f23'
down_revision: Union[str, Sequence[str], None] = 'f606535d5796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    # Add columns nullable first so existing rows don't violate NOT NULL
    op.add_column('transactions', sa.Column('provider_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('provider_tx_id', sa.String(), nullable=True))
    # Backfill existing rows so we can set NOT NULL
    conn = op.get_bind()
    conn.execute(sa.text(
        "UPDATE transactions SET provider_name = 'legacy', provider_tx_id = 'tx-' || id::text "
        "WHERE provider_name IS NULL"
    ))
    op.alter_column(
        'transactions', 'provider_name',
        existing_type=sa.String(),
        nullable=False
    )
    op.alter_column(
        'transactions', 'provider_tx_id',
        existing_type=sa.String(),
        nullable=False
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_unique_constraint('uq_provider_tx', 'transactions', ['provider_name', 'provider_tx_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_provider_tx', 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_column('transactions', 'provider_tx_id')
    op.drop_column('transactions', 'provider_name')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    # ### end Alembic commands ###
